name: Deploy Novo (Helm)

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy via Helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy com Helm
        run: |
          echo "Instalando chart de ./charts/"
          helm upgrade --install poc-new-app ./charts/
